CREATE TABLE [dbo].[States](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](25) NOT NULL
) ON [PRIMARY]

Insert into states values('Andaman and Nicobar')
Insert into states values('Andhra Pradesh')
Insert into states values('Arunachal Pradesh')
Insert into states values('Assam')
Insert into states values('Bihar')
Insert into states values('Chandigarh')
Insert into states values('Chhattisgarh')
Insert into states values('Dadra and Nagar Haveli')
Insert into states values('Daman and Diu')
Insert into states values('Delhi')
Insert into states values('Goa')
Insert into states values('Gujarat')
Insert into states values('Haryana')
Insert into states values('Himachal Pradesh')
Insert into states values('Jammu and Kashmir')
Insert into states values('Jharkhand')
Insert into states values('Karnataka')
Insert into states values('Kerala')
Insert into states values('Lakshadweep')
Insert into states values('Madhya Pradesh')
Insert into states values('Maharashtra')
Insert into states values('Manipur')
Insert into states values('Meghalaya')
Insert into states values('Mizoram')
Insert into states values('Nagaland')
Insert into states values('Orissa')
Insert into states values('Pondicherry')
Insert into states values('Punjab')
Insert into states values('Rajasthan')
Insert into states values('Sikkim')
Insert into states values('Tamil Nadu')
Insert into states values('Tripura')
Insert into states values('Uttaranchal')
Insert into states values('Uttar Pradesh')
Insert into states values('West Bengal')
